export const notes = [
  {
    id: "0",
    text: "Note 1",
    archived: true,
    createdTime: "7/30/2021",
    category: "Task",
  },
  {
    id: "1",
    text: "Note 2",
    archived: true,
    createdTime: "8/15/2021",
    category: "Random Thought",
  },
  {
    id: "2",
    text: "Note 3",
    archived: false,
    createdTime: "9/22/2021",
    category: "Idea",
  },
  {
    id: "3",
    text: "Note 4",
    archived: false,
    createdTime: "11/12/2021",
    category: "Task",
  },
  {
    id: "4",
    text: "Note 5",
    archived: false,
    createdTime: "1/1/2022",
    category: "Random Thought",
  },
  {
    id: "5",
    text: "Note 6",
    archived: false,
    createdTime: "3/18/2022",
    category: "Idea",
  },
  {
    id: "6",
    text: "Note 7",
    archived: false,
    createdTime: "6/24/2022",
    category: "Task",
  },
];
